version: '3'

services:
    db:
        image: mysql:8.0.20
        container_name: ${MYSQL_HOST}
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - symfony
    php:
        build:
            context: .
            dockerfile: build/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./:/app/
        networks:
            - symfony
    nginx:
        build:
            context: .
            dockerfile: build/nginx/Dockerfile
        volumes:
            - ./:/app/
        ports:
            - 80:80
        networks:
            - symfony

volumes:
    db_app:

networks:
    symfony:
